<?php
require_once __DIR__ . '/db.php';

function syncProducts() {
    $db = getDB();

    $products = $db->query("SELECT * FROM products ORDER BY id")->fetchAll();

    $sections = [
        'homeFourPicksProducts' => [1, 5],
        'topRateProducts' => [6, 11],
        'topItemsProducts' => [12, 17],
        'categoryPromoProducts' => [18, 21],
        'mostLovedProducts' => [22, 27],
        'productsSectionProducts' => [28, 37],
        'limitedTimeProducts' => [38, 47],
        'favouriteCategoryProducts' => [48, 51],
    ];

    $output = "<?php\n";
    $output .= "/**\n";
    $output .= " * Product Data Arrays - AUTO-GENERATED BY ADMIN PANEL\n";
    $output .= " * Do not edit manually. Changes will be overwritten.\n";
    $output .= " * Last synced: " . date('Y-m-d H:i:s') . "\n";
    $output .= " */\n\n";

    $allProductIds = [];

    foreach ($sections as $varName => [$minId, $maxId]) {
        $output .= "// {$varName}\n";
        $output .= "\${$varName} = [\n";

        $sectionProducts = array_filter($products, function($p) use ($minId, $maxId) {
            return $p['id'] >= $minId && $p['id'] <= $maxId;
        });

        foreach ($sectionProducts as $product) {
            $allProductIds[] = $product['id'];
            $output .= "    [\n";
            $output .= "        'id' => {$product['id']},\n";
            $output .= "        'name' => " . var_export($product['name'], true) . ",\n";
            $output .= "        'category' => " . var_export($product['category'], true) . ",\n";
            $output .= "        'image' => " . var_export($product['image'], true) . ",\n";
            $output .= "        'url' => 'product-details.php',\n";
            $output .= "        'current_price' => " . var_export($product['current_price'], true) . ",\n";
            $output .= "        'old_price' => " . var_export($product['old_price'] ?? '', true) . ",\n";
            $output .= "        'discount_percentage' => " . var_export($product['discount_percentage'] ?? '', true) . ",\n";
            $output .= "        'discount_badge' => " . var_export($product['discount_badge'] ?? '', true) . ",\n";
            $output .= "        'rating' => " . var_export((float)$product['rating'], true) . ",\n";
            $output .= "        'reviews' => {$product['reviews']},\n";
            $output .= "        'sold' => {$product['sold']},\n";
            $output .= "        'available' => {$product['available']}\n";
            $output .= "    ],\n";
        }

        $output .= "];\n\n";
    }

    // Catch-all for new products beyond predefined sections
    $allProductIds = [];
    foreach ($sections as [$minId, $maxId]) {
        for ($i = $minId; $i <= $maxId; $i++) {
            $allProductIds[] = $i;
        }
    }
    $maxPredefinedId = 51;
    $remainingProducts = array_filter($products, function($p) use ($maxPredefinedId) {
        return $p['id'] > $maxPredefinedId;
    });
    if (!empty($remainingProducts)) {
        $output .= "// New Arrivals (catch-all for products beyond predefined sections)\n";
        $output .= "\$newArrivalsProducts = [\n";
        foreach ($remainingProducts as $product) {
            $output .= "    [\n";
            $output .= "        'id' => {$product['id']},\n";
            $output .= "        'name' => " . var_export($product['name'], true) . ",\n";
            $output .= "        'category' => " . var_export($product['category'], true) . ",\n";
            $output .= "        'image' => " . var_export($product['image'], true) . ",\n";
            $output .= "        'url' => 'product-details.php',\n";
            $output .= "        'current_price' => " . var_export($product['current_price'], true) . ",\n";
            $output .= "        'old_price' => " . var_export($product['old_price'] ?? '', true) . ",\n";
            $output .= "        'discount_percentage' => " . var_export($product['discount_percentage'] ?? '', true) . ",\n";
            $output .= "        'discount_badge' => " . var_export($product['discount_badge'] ?? '', true) . ",\n";
            $output .= "        'rating' => " . var_export((float)$product['rating'], true) . ",\n";
            $output .= "        'reviews' => {$product['reviews']},\n";
            $output .= "        'sold' => {$product['sold']},\n";
            $output .= "        'available' => {$product['available']}\n";
            $output .= "    ],\n";
        }
        $output .= "];\n\n";
    } else {
        $output .= "\$newArrivalsProducts = [];\n\n";
    }

    // Category cards (static)
    $output .= "// Category Cards\n";
    $output .= "\$categoryCards = [\n";
    $categoryCards = [
        ['id' => 1, 'name' => 'Lippan Art Mirrors', 'image' => 'images/product/p-1.jpeg', 'url' => '#'],
        ['id' => 2, 'name' => 'Mandala Wall Art', 'image' => 'images/product/p-2.png', 'url' => '#'],
        ['id' => 3, 'name' => 'Lippan Wall Panels', 'image' => 'images/product/p-3.jpeg', 'url' => '#'],
        ['id' => 4, 'name' => 'Dot Mandala Decor', 'image' => 'images/product/p-4.png', 'url' => '#'],
        ['id' => 5, 'name' => 'Lippan Photo Frames', 'image' => 'images/product/p-5.jpeg', 'url' => '#'],
        ['id' => 6, 'name' => 'Mandala Clocks', 'image' => 'images/product/p-6.png', 'url' => '#'],
        ['id' => 7, 'name' => 'Decorative Plates', 'image' => 'images/product/p-1.jpeg', 'url' => '#'],
        ['id' => 8, 'name' => 'Mandala Tableware', 'image' => 'images/product/p-2.png', 'url' => '#'],
    ];
    foreach ($categoryCards as $card) {
        $output .= "    ['id' => {$card['id']}, 'name' => '{$card['name']}', 'image' => '{$card['image']}', 'url' => '{$card['url']}'],\n";
    }
    $output .= "];\n\n";

    // Size options (static defaults)
    $output .= "// Product Size Options\n";
    $output .= "\$productSizeOptions = [\n";
    $output .= "    'small' => ['label' => 'Small', 'dimension' => '6\" - 8\"', 'price_multiplier' => 0.6],\n";
    $output .= "    'medium' => ['label' => 'Medium', 'dimension' => '10\" - 14\"', 'price_multiplier' => 1.0],\n";
    $output .= "    'large' => ['label' => 'Large', 'dimension' => '16\" - 24\"', 'price_multiplier' => 1.6],\n";
    $output .= "    'x_large' => ['label' => 'Extra Large', 'dimension' => '30\" - 36\"', 'price_multiplier' => 2.4],\n";
    $output .= "    'custom' => ['label' => 'Custom Size', 'dimension' => 'As Required', 'price_multiplier' => 0],\n";
    $output .= "];\n\n";

    // Color options (static defaults)
    $output .= "// Product Color Options\n";
    $output .= "\$productColorOptions = [\n";
    $output .= "    ['label' => 'Natural White', 'hex' => '#F5F0E8'],\n";
    $output .= "    ['label' => 'Cream Beige', 'hex' => '#E8D5B7'],\n";
    $output .= "    ['label' => 'Terracotta', 'hex' => '#C67B5C'],\n";
    $output .= "    ['label' => 'Multicolor', 'hex' => 'linear-gradient(135deg, #E8D5B7, #C67B5C, #8B5E3C)'],\n";
    $output .= "    ['label' => 'Gold Accent', 'hex' => '#D4A843'],\n";
    $output .= "    ['label' => 'Mirror Work', 'hex' => '#C0C0C0'],\n";
    $output .= "];\n\n";

    // Material options (static defaults)
    $output .= "// Product Material Options\n";
    $output .= "\$productMaterialOptions = [\n";
    $output .= "    'pop_clay' => ['label' => 'POP Clay', 'description' => 'Lightweight and durable'],\n";
    $output .= "    'mdf_board' => ['label' => 'MDF Board', 'description' => 'Engineered wood base'],\n";
    $output .= "    'wooden' => ['label' => 'Wooden Base', 'description' => 'Natural wood framework'],\n";
    $output .= "    'canvas' => ['label' => 'Canvas', 'description' => 'Stretched canvas'],\n";
    $output .= "    'iron_metal' => ['label' => 'Iron/Metal', 'description' => 'Metal framework'],\n";
    $output .= "    'terracotta' => ['label' => 'Terracotta', 'description' => 'Natural clay material'],\n";
    $output .= "];\n\n";

    // Filter options (static)
    $output .= "// Shop Filter Options\n";
    $output .= "\$shopFilterOptions = [\n";
    $output .= "    'categories' => [['label' => 'All Categories', 'count' => " . count($products) . "], ['label' => 'Lippan Art', 'count' => 0], ['label' => 'Mandala Art', 'count' => 0]],\n";
    $output .= "    'sizes' => [['label' => 'Small (6\" - 8\")'], ['label' => 'Medium (10\" - 14\")'], ['label' => 'Large (16\" - 24\")'], ['label' => 'Extra Large (30\" - 36\")'], ['label' => 'Custom Size']],\n";
    $output .= "    'price_ranges' => [['label' => 'Under ₹1,000', 'min' => 0, 'max' => 1000], ['label' => '₹1,000 - ₹2,000', 'min' => 1000, 'max' => 2000], ['label' => '₹2,000 - ₹3,000', 'min' => 2000, 'max' => 3000], ['label' => '₹3,000 - ₹5,000', 'min' => 3000, 'max' => 5000], ['label' => '₹5,000 - ₹10,000', 'min' => 5000, 'max' => 10000], ['label' => 'Above ₹10,000', 'min' => 10000, 'max' => 999999]],\n";
    $output .= "    'materials' => [['label' => 'POP Clay'], ['label' => 'MDF Board'], ['label' => 'Wooden Base'], ['label' => 'Canvas'], ['label' => 'Iron/Metal'], ['label' => 'Terracotta']],\n";
    $output .= "    'ratings' => [['label' => '4 ★ & Above'], ['label' => '3 ★ & Above'], ['label' => '2 ★ & Above']],\n";
    $output .= "    'sort_options' => [['label' => 'Featured'], ['label' => 'Price: Low to High'], ['label' => 'Price: High to Low'], ['label' => 'Name: A-Z'], ['label' => 'Name: Z-A'], ['label' => 'Newest First']],\n";
    $output .= "];\n\n";

    // Variants example
    $output .= "// Product Variants Example\n";
    $output .= "\$productVariantsExample = [\n";
    $variants = $db->query("SELECT * FROM product_sizes WHERE product_id = 1")->fetchAll();
    foreach ($variants as $v) {
        $output .= "    ['variant_id' => {$v['id']}, 'product_id' => 1, 'size' => " . var_export($v['size_label'], true) . ", 'dimension' => " . var_export($v['dimension'] ?? '', true) . ", 'current_price' => '', 'old_price' => '', 'weight' => '', 'sku' => '', 'available' => 0],\n";
    }
    if (empty($variants)) {
        $output .= "    ['variant_id' => 1, 'product_id' => 1, 'size' => 'Small', 'dimension' => '6\" - 8\"', 'current_price' => '', 'old_price' => '', 'weight' => '', 'sku' => '', 'available' => 0],\n";
    }
    $output .= "];\n\n";

    // getProductById function
    $output .= <<<'FUNC'
function getProductById($productId) {
    global $homeFourPicksProducts, $topRateProducts, $topItemsProducts, $categoryPromoProducts, 
           $mostLovedProducts, $productsSectionProducts, $limitedTimeProducts, $favouriteCategoryProducts,
           $newArrivalsProducts;
    
    $allProducts = array_merge(
        $homeFourPicksProducts ?? [],
        $topRateProducts ?? [],
        $topItemsProducts ?? [],
        $categoryPromoProducts ?? [],
        $mostLovedProducts ?? [],
        $productsSectionProducts ?? [],
        $limitedTimeProducts ?? [],
        $favouriteCategoryProducts ?? [],
        $newArrivalsProducts ?? []
    );
    
    foreach ($allProducts as $product) {
        if (isset($product['id']) && $product['id'] == $productId) {
            $dbConnected = false;
            if (file_exists(__DIR__ . '/../admin/includes/db.php') && file_exists(__DIR__ . '/../config/database.php')) {
                try {
                    require_once __DIR__ . '/../admin/includes/db.php';
                    $db = getDB();
                    $stmt = $db->prepare("SELECT * FROM products WHERE id = ?");
                    $stmt->execute([$productId]);
                    $dbProduct = $stmt->fetch();
                    if ($dbProduct) {
                        $dbConnected = true;
                        $product['description'] = $dbProduct['description'] ?? '';
                        $product['materials'] = $dbProduct['materials'] ?? '';
                        $product['dimensions'] = $dbProduct['dimensions'] ?? '';
                        $product['weight'] = $dbProduct['weight'] ?? '';
                        $product['care_instructions'] = $dbProduct['care_instructions'] ?? '';
                        $product['sku'] = $dbProduct['sku'] ?? ('SKU-' . str_pad($product['id'], 3, '0', STR_PAD_LEFT));
                        
                        $imgs = $db->prepare("SELECT image_path FROM product_images WHERE product_id = ? ORDER BY sort_order");
                        $imgs->execute([$productId]);
                        $images = $imgs->fetchAll(PDO::FETCH_COLUMN);
                        $product['images'] = !empty($images) ? $images : [$product['image']];
                        
                        $sizes = $db->prepare("SELECT size_label FROM product_sizes WHERE product_id = ?");
                        $sizes->execute([$productId]);
                        $sizeLabels = $sizes->fetchAll(PDO::FETCH_COLUMN);
                        $product['size_options'] = !empty($sizeLabels) ? $sizeLabels : ['Small', 'Medium', 'Large', 'Extra Large'];
                        
                        $colors = $db->prepare("SELECT color_name as name, color_hex as hex, color_image as image FROM product_colors WHERE product_id = ?");
                        $colors->execute([$productId]);
                        $colorOpts = $colors->fetchAll();
                        $product['color_options'] = !empty($colorOpts) ? $colorOpts : [
                            ['name' => 'Natural White', 'hex' => '#F5F0E8', 'image' => ''],
                            ['name' => 'Cream Beige', 'hex' => '#E8D5B7', 'image' => ''],
                            ['name' => 'Terracotta', 'hex' => '#C67B5C', 'image' => ''],
                            ['name' => 'Multicolor', 'hex' => 'linear-gradient(135deg, #E8D5B7, #C67B5C, #8B5E3C)', 'image' => '']
                        ];
                        
                        $info = $db->prepare("SELECT info_key, info_value FROM product_additional_info WHERE product_id = ?");
                        $info->execute([$productId]);
                        $infoRows = $info->fetchAll();
                        $additionalInfo = [];
                        foreach ($infoRows as $row) {
                            $additionalInfo[$row['info_key']] = $row['info_value'];
                        }
                        $product['additional_info'] = !empty($additionalInfo) ? $additionalInfo : [];
                    }
                } catch (Exception $e) {
                    // DB not available, use defaults
                }
            }
            if (!$dbConnected) {
                $product['images'] = [$product['image']];
                $product['description'] = '';
                $product['materials'] = '';
                $product['dimensions'] = '';
                $product['weight'] = '';
                $product['care_instructions'] = '';
                $product['sku'] = 'SKU-' . str_pad($product['id'], 3, '0', STR_PAD_LEFT);
                $product['size_options'] = ['Small', 'Medium', 'Large', 'Extra Large'];
                $product['color_options'] = [['name' => 'Natural White', 'hex' => '#F5F0E8', 'image' => '']];
                $product['additional_info'] = [];
            }
            return $product;
        }
    }
    
    return [
        'id' => 1,
        'name' => 'Product',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-1.jpeg',
        'images' => ['images/product/p-1.jpeg'],
        'current_price' => '₹0',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => '',
        'rating' => 0,
        'reviews' => 0,
        'sold' => 0,
        'available' => 0,
        'description' => '',
        'materials' => '',
        'dimensions' => '',
        'weight' => '',
        'care_instructions' => '',
        'sku' => 'SKU-001',
        'size_options' => ['Small', 'Medium', 'Large'],
        'color_options' => [['name' => 'Natural White', 'hex' => '#F5F0E8']],
        'additional_info' => []
    ];
}

function getRelatedProducts($currentProductId, $category = null, $limit = 4) {
    global $homeFourPicksProducts, $topRateProducts, $topItemsProducts, $categoryPromoProducts, 
           $mostLovedProducts, $productsSectionProducts, $limitedTimeProducts, $favouriteCategoryProducts,
           $newArrivalsProducts;
    
    $allProducts = array_merge(
        $homeFourPicksProducts ?? [],
        $topRateProducts ?? [],
        $topItemsProducts ?? [],
        $categoryPromoProducts ?? [],
        $mostLovedProducts ?? [],
        $productsSectionProducts ?? [],
        $limitedTimeProducts ?? [],
        $favouriteCategoryProducts ?? [],
        $newArrivalsProducts ?? []
    );
    
    $related = [];
    foreach ($allProducts as $product) {
        if (isset($product['id']) && $product['id'] != $currentProductId) {
            if ($category === null || $product['category'] === $category) {
                $related[] = $product;
                if (count($related) >= $limit) break;
            }
        }
    }
    
    if (count($related) < $limit) {
        foreach ($allProducts as $product) {
            if (isset($product['id']) && $product['id'] != $currentProductId) {
                $found = false;
                foreach ($related as $r) {
                    if ($r['id'] == $product['id']) { $found = true; break; }
                }
                if (!$found) {
                    $related[] = $product;
                    if (count($related) >= $limit) break;
                }
            }
        }
    }
    
    return array_slice($related, 0, $limit);
}
FUNC;

    $output .= "\n";
    $output .= "?>";

    file_put_contents(__DIR__ . '/../../data/products.php', $output);
}

function syncBlogs() {
    $db = getDB();
    $blogs = $db->query("SELECT * FROM blogs ORDER BY id")->fetchAll();

    $output = "<?php\n";
    $output .= "// Blog Data - AUTO-GENERATED BY ADMIN PANEL\n";
    $output .= "// Do not edit manually. Changes will be overwritten.\n";
    $output .= "// Last synced: " . date('Y-m-d H:i:s') . "\n\n";
    $output .= "\$blogs = [\n";

    foreach ($blogs as $blog) {
        $output .= "    [\n";
        $output .= "        'id' => {$blog['id']},\n";
        $output .= "        'title' => " . var_export($blog['title'], true) . ",\n";
        $output .= "        'slug' => " . var_export($blog['slug'], true) . ",\n";
        $output .= "        'category' => " . var_export($blog['category'], true) . ",\n";
        $output .= "        'category_color' => " . var_export($blog['category_color'] ?? 'primary', true) . ",\n";
        $output .= "        'image' => " . var_export($blog['image'], true) . ",\n";
        $output .= "        'excerpt' => " . var_export($blog['excerpt'], true) . ",\n";
        $output .= "        'content' => " . var_export($blog['content'], true) . ",\n";
        $output .= "        'meta_title' => " . var_export($blog['meta_title'] ?? '', true) . ",\n";
        $output .= "        'meta_description' => " . var_export($blog['meta_description'] ?? '', true) . ",\n";
        $output .= "        'author' => " . var_export($blog['author'] ?? 'KiraCollection', true) . ",\n";
        $output .= "        'author_image' => " . var_export($blog['author_image'] ?? 'assets/images/home-3/hot-sauce-bg.jpg', true) . ",\n";
        $output .= "        'date' => " . var_export($blog['date'], true) . ",\n";
        $output .= "        'reading_time' => " . var_export($blog['reading_time'] ?? '', true) . ",\n";
        $output .= "        'comments' => {$blog['comments']},\n";
        $output .= "        'views' => {$blog['views']},\n";

        // Tags
        $stmt = $db->prepare("SELECT tag FROM blog_tags WHERE blog_id = ?");
        $stmt->execute([$blog['id']]);
        $tags = $stmt->fetchAll(PDO::FETCH_COLUMN);
        $output .= "        'tags' => " . var_export($tags, true) . ",\n";

        $output .= "    ],\n";
    }

    $output .= "];\n\n";

    // Blog categories
    $output .= "// Blog categories\n";
    $output .= "\$blog_categories = [\n";
    $catStmt = $db->query("SELECT category, COUNT(*) as cnt FROM blogs GROUP BY category");
    $categories = $catStmt->fetchAll();
    foreach ($categories as $cat) {
        $output .= "    " . var_export($cat['category'], true) . " => {$cat['cnt']},\n";
    }
    if (empty($categories)) {
        $output .= "    'Lippan Art' => 0,\n";
    }
    $output .= "];\n\n";

    // Popular tags
    $output .= "// Popular tags\n";
    $output .= "\$popular_tags = ['Traditional Art', 'Mandala', 'Home Decor', 'DIY', 'Spirituality', 'Interior Design', 'Artisan Stories', 'Meditation'];\n\n";
    $output .= "?>";

    file_put_contents(__DIR__ . '/../../data/blogs.php', $output);
}

function syncTestimonials() {
    $db = getDB();
    $testimonials = $db->query("SELECT * FROM testimonials WHERE is_active = 1 ORDER BY sort_order ASC, id ASC")->fetchAll();

    $output = "<?php\n";
    $output .= "// Testimonial Data - AUTO-GENERATED BY ADMIN PANEL\n";
    $output .= "// Do not edit manually. Changes will be overwritten.\n";
    $output .= "// Last synced: " . date('Y-m-d H:i:s') . "\n\n";
    $output .= "\$testimonials = [\n";

    foreach ($testimonials as $t) {
        $output .= "    [\n";
        $output .= "        'id' => {$t['id']},\n";
        $output .= "        'name' => " . var_export($t['name'], true) . ",\n";
        $output .= "        'designation' => " . var_export($t['designation'] ?? '', true) . ",\n";
        $output .= "        'content' => " . var_export($t['content'], true) . ",\n";
        $output .= "        'image' => " . var_export($t['image'] ?? '', true) . ",\n";
        $output .= "        'rating' => {$t['rating']},\n";
        $output .= "        'sort_order' => {$t['sort_order']},\n";
        $output .= "    ],\n";
    }

    $output .= "];\n";
    $output .= "?>";
    file_put_contents(__DIR__ . '/../../data/testimonials.php', $output);
}
