<!-- Reset Password Page Sidebar Start -->
<div data-state="close" class="reset-password-page-sidebar fixed xl:top-[30px] xl:right-[22px] right-0 top-0 xl:h-[calc(100vh-52px)] h-full z-99 max-w-[600px] w-full bg-white xl:rounded-2xl rounded-none transition-all duration-250 ease-[cubic-bezier(0.645,0.045,0.355,1)] data-[state=open]:translate-x-0 data-[state=open]:opacity-100 data-[state=open]:visible data-[state=close]:translate-x-[200px] data-[state=close]:opacity-0 data-[state=close]:invisible">
    <div class="reset-password-page-sidebar-header px-6 pt-6 pb-4 border-b border-gray-300 relative"><h5>Reset Password</h5><button data-close-sidebar=".reset-password-page-sidebar" class="close-sidebar-btn absolute top-1/2 right-6 -translate-y-1/2 cursor-pointer inline-flex items-center justify-center size-9 rounded-full bg-[rgba(145,158,171,0.08)]"><i class="hgi hgi-stroke hgi-multiplication-sign text-xl leading-5 text-light-primary-text"></i></button></div>
    <div class="reset-password-page-sidebar-content p-10 flex flex-col gap-y-10 overflow-y-auto max-h-[calc(100%-70px)]">
        <div class="image-wrapper mx-auto"><img src="assets/images/authentication/reset-illustration.png" alt="reset-password" /></div>
        <div class="reset-password-form"><form class="flex flex-col gap-y-6"><div class="relative w-full"><input type="password" id="reset-password" class="peer form-control input-group medium rounded-[80px] px-3.5 placeholder-transparent focus:placeholder-transparent focus:outline-none" placeholder="Password *" /><label for="reset-password" class="absolute left-[14px] top-1/2 -translate-y-1/2 text-xs leading-[18px] transition-all peer-placeholder-shown:text-light-disabled-text peer-focus:text-light-disabled-text peer-placeholder-shown:text-[16px] peer-placeholder-shown:top-1/2 peer-focus:text-[12px] peer-focus:top-0 peer-[:not(:placeholder-shown)]:text-[12px] peer-[:not(:placeholder-shown)]:top-0 bg-white peer-focus:px-1 peer-[:not(:placeholder-shown)]:px-1">Password *</label></div><div class="relative w-full"><input type="password" id="reset-confirm-password" class="peer form-control input-group medium rounded-[80px] px-3.5 placeholder-transparent focus:placeholder-transparent focus:outline-none" placeholder="Confirm Password *" /><label for="reset-confirm-password" class="absolute left-[14px] top-1/2 -translate-y-1/2 text-xs leading-[18px] transition-all peer-placeholder-shown:text-light-disabled-text peer-focus:text-light-disabled-text peer-placeholder-shown:text-[16px] peer-placeholder-shown:top-1/2 peer-focus:text-[12px] peer-focus:top-0 peer-[:not(:placeholder-shown)]:text-[12px] peer-[:not(:placeholder-shown)]:top-0 bg-white peer-focus:px-1 peer-[:not(:placeholder-shown)]:px-1">Confirm Password *</label></div><div><button class="btn btn-primary btn-large rounded-[80px] w-full">Change Password</button></div></form></div>
        <div class="back-to-login-section"><a class="text-primary login-page-btn font-semibold leading-[26px]" href="#">Back to Login</a></div>
    </div>
</div>
<!-- Reset Password Page Sidebar End -->
