<?php
// Blog Data - AUTO-GENERATED BY ADMIN PANEL
// Do not edit manually. Changes will be overwritten.
// Last synced: 2026-05-17 17:06:39

$blogs = [
];

// Blog categories
$blog_categories = [
    'Lippan Art' => 0,
];

// Popular tags
$popular_tags = ['Traditional Art', 'Mandala', 'Home Decor', 'DIY', 'Spirituality', 'Interior Design', 'Artisan Stories', 'Meditation'];

?>