<?php
/**
 * Product Data Arrays - AUTO-GENERATED BY ADMIN PANEL
 * Do not edit manually. Changes will be overwritten.
 * Last synced: 2026-05-17 16:44:31
 */

// homeFourPicksProducts
$homeFourPicksProducts = [
    [
        'id' => 1,
        'name' => 'Traditional Lippan Art Mirror Frame - Peacock Design',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹2,499',
        'old_price' => '₹3,199',
        'discount_percentage' => '22% OFF',
        'discount_badge' => 'BESTSELLER',
        'rating' => 5.0,
        'reviews' => 234,
        'sold' => 89,
        'available' => 45
    ],
    [
        'id' => 2,
        'name' => 'Sacred Geometry Mandala Wall Art - Lotus',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹1,899',
        'old_price' => '₹2,499',
        'discount_percentage' => '24% OFF',
        'discount_badge' => 'SALES',
        'rating' => 4.5,
        'reviews' => 178,
        'sold' => 67,
        'available' => 60
    ],
    [
        'id' => 3,
        'name' => 'Handcrafted Lippan Art Wall Panel - Tree of Life',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹4,999',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => 'NEW',
        'rating' => 5.0,
        'reviews' => 56,
        'sold' => 12,
        'available' => 20
    ],
    [
        'id' => 4,
        'name' => 'Dot Mandala Coaster Set - Pack of 6',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹699',
        'old_price' => '₹899',
        'discount_percentage' => '22% OFF',
        'discount_badge' => 'SALES',
        'rating' => 4.5,
        'reviews' => 312,
        'sold' => 145,
        'available' => 200
    ],
    [
        'id' => 5,
        'name' => 'Lippan Art Decorative Plate - Circular Motif',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹999',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => '',
        'rating' => 4.0,
        'reviews' => 98,
        'sold' => 54,
        'available' => 80
    ],
];

// topRateProducts
$topRateProducts = [
    [
        'id' => 6,
        'name' => 'Large Mandala Canvas Print - Cosmic Spiral (24")',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹3,499',
        'old_price' => '₹4,299',
        'discount_percentage' => '19% OFF',
        'discount_badge' => 'POPULAR',
        'rating' => 5.0,
        'reviews' => 456,
        'sold' => 123,
        'available' => 35
    ],
    [
        'id' => 7,
        'name' => 'Lippan Art Room Divider Panel - 3 Panel Set',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹8,999',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => 'PREMIUM',
        'rating' => 5.0,
        'reviews' => 89,
        'sold' => 18,
        'available' => 10
    ],
    [
        'id' => 8,
        'name' => 'Mandala Wooden Wall Clock - 16" Diameter',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹2,199',
        'old_price' => '₹2,799',
        'discount_percentage' => '21% OFF',
        'discount_badge' => 'SALES',
        'rating' => 4.5,
        'reviews' => 267,
        'sold' => 78,
        'available' => 40
    ],
    [
        'id' => 9,
        'name' => 'Mini Lippan Art Frame Set - Pack of 3 (8" each)',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹1,499',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => '',
        'rating' => 4.5,
        'reviews' => 198,
        'sold' => 92,
        'available' => 110
    ],
    [
        'id' => 10,
        'name' => 'Mandala Dreamcatcher Wall Hanging - Feather Design',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹1,299',
        'old_price' => '₹1,699',
        'discount_percentage' => '24% OFF',
        'discount_badge' => 'SALES',
        'rating' => 4.5,
        'reviews' => 334,
        'sold' => 156,
        'available' => 75
    ],
    [
        'id' => 11,
        'name' => 'Lippan Art Photo Frame - 12" x 16" with Mirror Work',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹1,799',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => '',
        'rating' => 4.0,
        'reviews' => 145,
        'sold' => 63,
        'available' => 55
    ],
];

// topItemsProducts
$topItemsProducts = [
    [
        'id' => 12,
        'name' => 'Lippan Art Round Wall Plate - 18" with Traditional Motifs',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹2,299',
        'old_price' => '₹2,999',
        'discount_percentage' => '23% OFF',
        'discount_badge' => 'HOT',
        'rating' => 5.0,
        'reviews' => 289,
        'sold' => 167,
        'available' => 50
    ],
    [
        'id' => 13,
        'name' => 'Dot Mandala Painted Tray - Serving & Decor (14")',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹899',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => '',
        'rating' => 4.5,
        'reviews' => 213,
        'sold' => 134,
        'available' => 90
    ],
    [
        'id' => 14,
        'name' => 'Lippan Art Entrance Door Frame Decor - 36" x 80"',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹6,499',
        'old_price' => '₹8,499',
        'discount_percentage' => '24% OFF',
        'discount_badge' => 'SALES',
        'rating' => 5.0,
        'reviews' => 76,
        'sold' => 28,
        'available' => 15
    ],
    [
        'id' => 15,
        'name' => 'Mandala String Art - Heart Pattern (12")',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹1,199',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => 'TRENDING',
        'rating' => 5.0,
        'reviews' => 423,
        'sold' => 201,
        'available' => 120
    ],
    [
        'id' => 16,
        'name' => 'Lippan Art Pooja Room Panel - Om & Swastik Design',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹3,799',
        'old_price' => '₹4,999',
        'discount_percentage' => '24% OFF',
        'discount_badge' => 'SALES',
        'rating' => 5.0,
        'reviews' => 167,
        'sold' => 74,
        'available' => 30
    ],
    [
        'id' => 17,
        'name' => 'Mandala LED Backlit Wall Art - Glowing Spiral (20")',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹2,999',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => 'NEW',
        'rating' => 4.5,
        'reviews' => 92,
        'sold' => 41,
        'available' => 35
    ],
];

// categoryPromoProducts
$categoryPromoProducts = [
    [
        'id' => 18,
        'name' => 'Grand Lippan Art Feature Wall Kit - 8ft x 10ft',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹14,999',
        'old_price' => '₹19,999',
        'discount_percentage' => '25% OFF',
        'discount_badge' => 'DEAL',
        'rating' => 5.0,
        'reviews' => 34,
        'sold' => 8,
        'available' => 10
    ],
    [
        'id' => 19,
        'name' => 'Mandala MDF Cutout Set - DIY Painting (6" Set of 8)',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹599',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => '',
        'rating' => 4.0,
        'reviews' => 156,
        'sold' => 234,
        'available' => 300
    ],
    [
        'id' => 20,
        'name' => 'Lippan Art TV Unit Backdrop Panel - 6ft x 4ft',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹9,999',
        'old_price' => '₹12,999',
        'discount_percentage' => '23% OFF',
        'discount_badge' => 'SALES',
        'rating' => 5.0,
        'reviews' => 45,
        'sold' => 14,
        'available' => 12
    ],
    [
        'id' => 21,
        'name' => 'Mandala Stained Glass Suncatcher - Rainbow (10")',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹1,599',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => '',
        'rating' => 4.5,
        'reviews' => 189,
        'sold' => 87,
        'available' => 65
    ],
];

// mostLovedProducts
$mostLovedProducts = [
    [
        'id' => 22,
        'name' => 'Lippan Art Mirror Frame - Floral Border Design (12" Round)',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹1,899',
        'old_price' => '₹2,399',
        'discount_percentage' => '21% OFF',
        'discount_badge' => '',
        'rating' => 5.0,
        'reviews' => 367,
        'sold' => 189,
        'available' => 70
    ],
    [
        'id' => 23,
        'name' => 'Mandala Wall Painting - Acrylic on Canvas (18" Square)',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹2,799',
        'old_price' => '₹3,499',
        'discount_percentage' => '20% OFF',
        'discount_badge' => '',
        'rating' => 5.0,
        'reviews' => 298,
        'sold' => 145,
        'available' => 40
    ],
    [
        'id' => 24,
        'name' => 'Lippan Art Rectangle Panel - Elephant Motif (24" x 18")',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹3,299',
        'old_price' => '₹4,199',
        'discount_percentage' => '21% OFF',
        'discount_badge' => '',
        'rating' => 4.5,
        'reviews' => 234,
        'sold' => 112,
        'available' => 35
    ],
    [
        'id' => 25,
        'name' => 'Mandala Table Lamp - Ceramic Handpainted (8" Height)',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹1,499',
        'old_price' => '₹1,899',
        'discount_percentage' => '21% OFF',
        'discount_badge' => '',
        'rating' => 4.5,
        'reviews' => 421,
        'sold' => 198,
        'available' => 55
    ],
    [
        'id' => 26,
        'name' => 'Lippan Art Key Holder - Multi Hook with Mirror (16")',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹999',
        'old_price' => '₹1,299',
        'discount_percentage' => '23% OFF',
        'discount_badge' => '',
        'rating' => 4.5,
        'reviews' => 345,
        'sold' => 223,
        'available' => 90
    ],
    [
        'id' => 27,
        'name' => 'Mandala Bookmark Set - Handpainted Metal (Set of 5)',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹399',
        'old_price' => '₹499',
        'discount_percentage' => '20% OFF',
        'discount_badge' => '',
        'rating' => 5.0,
        'reviews' => 512,
        'sold' => 389,
        'available' => 250
    ],
];

// productsSectionProducts
$productsSectionProducts = [
    [
        'id' => 28,
        'name' => 'Lippan Art Square Mirror - Geometric Pattern (10")',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹1,599',
        'old_price' => '₹1,999',
        'discount_percentage' => '20% OFF',
        'discount_badge' => '',
        'rating' => 4.5,
        'reviews' => 178,
        'sold' => 76,
        'available' => 65
    ],
    [
        'id' => 29,
        'name' => 'Mandala Wall Decal - Removable Vinyl (30" Circle)',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹799',
        'old_price' => '₹999',
        'discount_percentage' => '20% OFF',
        'discount_badge' => '',
        'rating' => 4.0,
        'reviews' => 234,
        'sold' => 156,
        'available' => 180
    ],
    [
        'id' => 30,
        'name' => 'Lippan Art Circle Frame - Abstract Waves (14" Round)',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹2,099',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => '',
        'rating' => 4.5,
        'reviews' => 145,
        'sold' => 58,
        'available' => 45
    ],
    [
        'id' => 31,
        'name' => 'Mandala Stone Painting Set - River Rock Art (Set of 4)',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹849',
        'old_price' => '₹1,099',
        'discount_percentage' => '23% OFF',
        'discount_badge' => '',
        'rating' => 5.0,
        'reviews' => 267,
        'sold' => 134,
        'available' => 100
    ],
    [
        'id' => 32,
        'name' => 'Lippan Art Headboard Panel - King Size (6ft Width)',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹7,999',
        'old_price' => '₹9,999',
        'discount_percentage' => '20% OFF',
        'discount_badge' => '',
        'rating' => 5.0,
        'reviews' => 67,
        'sold' => 19,
        'available' => 12
    ],
    [
        'id' => 33,
        'name' => 'Mandala Wind Chime - Bamboo & Metal (22" Length)',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹699',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => '',
        'rating' => 4.0,
        'reviews' => 189,
        'sold' => 98,
        'available' => 120
    ],
    [
        'id' => 34,
        'name' => 'Lippan Art Tray - Serving with Handles (16" Oval)',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹1,299',
        'old_price' => '₹1,699',
        'discount_percentage' => '24% OFF',
        'discount_badge' => '',
        'rating' => 4.5,
        'reviews' => 156,
        'sold' => 72,
        'available' => 55
    ],
    [
        'id' => 35,
        'name' => 'Mandala Journal - Handbound Leather (6" x 8")',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹599',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => '',
        'rating' => 4.5,
        'reviews' => 298,
        'sold' => 167,
        'available' => 140
    ],
    [
        'id' => 36,
        'name' => 'Lippan Art Console Table Top - Inlay Work (36" x 18")',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹5,499',
        'old_price' => '₹6,999',
        'discount_percentage' => '21% OFF',
        'discount_badge' => '',
        'rating' => 5.0,
        'reviews' => 45,
        'sold' => 11,
        'available' => 18
    ],
    [
        'id' => 37,
        'name' => 'Mandala Phone Stand - Resin Handmade (4" Base)',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹449',
        'old_price' => '₹599',
        'discount_percentage' => '25% OFF',
        'discount_badge' => '',
        'rating' => 4.0,
        'reviews' => 378,
        'sold' => 245,
        'available' => 200
    ],
];

// limitedTimeProducts
$limitedTimeProducts = [
    [
        'id' => 38,
        'name' => 'Lippan Art Hexagon Shelf Set - Wall Mounted (3 Pieces, 8" each)',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹1,799',
        'old_price' => '₹2,499',
        'discount_percentage' => '28% OFF',
        'discount_badge' => 'FLASH',
        'rating' => 4.5,
        'reviews' => 198,
        'sold' => 87,
        'available' => 25
    ],
    [
        'id' => 39,
        'name' => 'Mandala Tapestry - Cotton Printed (60" x 90")',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹899',
        'old_price' => '₹1,499',
        'discount_percentage' => '40% OFF',
        'discount_badge' => 'FLASH',
        'rating' => 4.5,
        'reviews' => 345,
        'sold' => 178,
        'available' => 40
    ],
    [
        'id' => 40,
        'name' => 'Lippan Art Clock - Round with Mirror Pieces (16")',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹1,999',
        'old_price' => '₹2,799',
        'discount_percentage' => '29% OFF',
        'discount_badge' => 'FLASH',
        'rating' => 5.0,
        'reviews' => 223,
        'sold' => 98,
        'available' => 20
    ],
    [
        'id' => 41,
        'name' => 'Mandala Candle Holder Set - Iron Craft (Set of 3, 4"/6"/8")',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹1,099',
        'old_price' => '₹1,699',
        'discount_percentage' => '35% OFF',
        'discount_badge' => 'FLASH',
        'rating' => 4.5,
        'reviews' => 267,
        'sold' => 134,
        'available' => 35
    ],
    [
        'id' => 42,
        'name' => 'Lippan Art Coaster Set - Pack of 4 with Holder (4" each)',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹599',
        'old_price' => '₹999',
        'discount_percentage' => '40% OFF',
        'discount_badge' => 'FLASH',
        'rating' => 4.0,
        'reviews' => 412,
        'sold' => 267,
        'available' => 60
    ],
    [
        'id' => 43,
        'name' => 'Mandala Floating Shelf - Wooden Cutout (12" x 12")',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹799',
        'old_price' => '₹1,199',
        'discount_percentage' => '33% OFF',
        'discount_badge' => 'FLASH',
        'rating' => 4.0,
        'reviews' => 156,
        'sold' => 78,
        'available' => 30
    ],
    [
        'id' => 44,
        'name' => 'Lippan Art Name Plate - Customizable (18" x 6")',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹899',
        'old_price' => '₹1,399',
        'discount_percentage' => '36% OFF',
        'discount_badge' => 'FLASH',
        'rating' => 5.0,
        'reviews' => 534,
        'sold' => 312,
        'available' => 80
    ],
    [
        'id' => 45,
        'name' => 'Mandala Table Runner - Handblock Printed (72" x 14")',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹649',
        'old_price' => '₹999',
        'discount_percentage' => '35% OFF',
        'discount_badge' => 'FLASH',
        'rating' => 4.5,
        'reviews' => 289,
        'sold' => 145,
        'available' => 70
    ],
    [
        'id' => 46,
        'name' => 'Lippan Art Pendant Lamp Shade - Dome Shape (10" Diameter)',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹1,499',
        'old_price' => '₹2,199',
        'discount_percentage' => '32% OFF',
        'discount_badge' => 'FLASH',
        'rating' => 4.5,
        'reviews' => 134,
        'sold' => 56,
        'available' => 22
    ],
    [
        'id' => 47,
        'name' => 'Mandala Pot Set - Terracotta Handpainted (4"/6"/8")',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹1,199',
        'old_price' => '₹1,899',
        'discount_percentage' => '37% OFF',
        'discount_badge' => 'FLASH',
        'rating' => 4.5,
        'reviews' => 198,
        'sold' => 89,
        'available' => 40
    ],
];

// favouriteCategoryProducts
$favouriteCategoryProducts = [
    [
        'id' => 48,
        'name' => 'Premium Lippan Art Wall Mural - Desert Scene (4ft x 6ft)',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹11,999',
        'old_price' => '₹15,999',
        'discount_percentage' => '25% OFF',
        'discount_badge' => 'PREMIUM',
        'rating' => 5.0,
        'reviews' => 23,
        'sold' => 6,
        'available' => 8
    ],
    [
        'id' => 49,
        'name' => 'Sacred Mandala Thangka Style Painting - Gold Leaf (24")',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-1.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹5,499',
        'old_price' => '₹6,999',
        'discount_percentage' => '21% OFF',
        'discount_badge' => 'PREMIUM',
        'rating' => 5.0,
        'reviews' => 67,
        'sold' => 28,
        'available' => 15
    ],
    [
        'id' => 50,
        'name' => 'Lippan Art Ceiling Medallion - Circular Rosette (24" Diameter)',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-2.png',
        'url' => 'product-detail.php',
        'current_price' => '₹3,999',
        'old_price' => '₹5,199',
        'discount_percentage' => '23% OFF',
        'discount_badge' => 'PREMIUM',
        'rating' => 5.0,
        'reviews' => 34,
        'sold' => 9,
        'available' => 12
    ],
    [
        'id' => 51,
        'name' => 'Mandala Floor Rug - Handwoven Jute (5ft Diameter Round)',
        'category' => 'Mandala Art',
        'image' => 'images/product/p-3.jpeg',
        'url' => 'product-detail.php',
        'current_price' => '₹3,299',
        'old_price' => '₹4,499',
        'discount_percentage' => '27% OFF',
        'discount_badge' => 'PREMIUM',
        'rating' => 4.5,
        'reviews' => 112,
        'sold' => 45,
        'available' => 25
    ],
];

$newArrivalsProducts = [];

// Category Cards
$categoryCards = [
    ['id' => 1, 'name' => 'Lippan Art Mirrors', 'image' => 'images/product/p-1.jpeg', 'url' => '#'],
    ['id' => 2, 'name' => 'Mandala Wall Art', 'image' => 'images/product/p-2.png', 'url' => '#'],
    ['id' => 3, 'name' => 'Lippan Wall Panels', 'image' => 'images/product/p-3.jpeg', 'url' => '#'],
    ['id' => 4, 'name' => 'Dot Mandala Decor', 'image' => 'images/product/p-4.png', 'url' => '#'],
    ['id' => 5, 'name' => 'Lippan Photo Frames', 'image' => 'images/product/p-5.jpeg', 'url' => '#'],
    ['id' => 6, 'name' => 'Mandala Clocks', 'image' => 'images/product/p-6.png', 'url' => '#'],
    ['id' => 7, 'name' => 'Decorative Plates', 'image' => 'images/product/p-1.jpeg', 'url' => '#'],
    ['id' => 8, 'name' => 'Mandala Tableware', 'image' => 'images/product/p-2.png', 'url' => '#'],
];

// Product Size Options
$productSizeOptions = [
    'small' => ['label' => 'Small', 'dimension' => '6" - 8"', 'price_multiplier' => 0.6],
    'medium' => ['label' => 'Medium', 'dimension' => '10" - 14"', 'price_multiplier' => 1.0],
    'large' => ['label' => 'Large', 'dimension' => '16" - 24"', 'price_multiplier' => 1.6],
    'x_large' => ['label' => 'Extra Large', 'dimension' => '30" - 36"', 'price_multiplier' => 2.4],
    'custom' => ['label' => 'Custom Size', 'dimension' => 'As Required', 'price_multiplier' => 0],
];

// Product Color Options
$productColorOptions = [
    ['label' => 'Natural White', 'hex' => '#F5F0E8'],
    ['label' => 'Cream Beige', 'hex' => '#E8D5B7'],
    ['label' => 'Terracotta', 'hex' => '#C67B5C'],
    ['label' => 'Multicolor', 'hex' => 'linear-gradient(135deg, #E8D5B7, #C67B5C, #8B5E3C)'],
    ['label' => 'Gold Accent', 'hex' => '#D4A843'],
    ['label' => 'Mirror Work', 'hex' => '#C0C0C0'],
];

// Product Material Options
$productMaterialOptions = [
    'pop_clay' => ['label' => 'POP Clay', 'description' => 'Lightweight and durable'],
    'mdf_board' => ['label' => 'MDF Board', 'description' => 'Engineered wood base'],
    'wooden' => ['label' => 'Wooden Base', 'description' => 'Natural wood framework'],
    'canvas' => ['label' => 'Canvas', 'description' => 'Stretched canvas'],
    'iron_metal' => ['label' => 'Iron/Metal', 'description' => 'Metal framework'],
    'terracotta' => ['label' => 'Terracotta', 'description' => 'Natural clay material'],
];

// Shop Filter Options
$shopFilterOptions = [
    'categories' => [['label' => 'All Categories', 'count' => 51], ['label' => 'Lippan Art', 'count' => 0], ['label' => 'Mandala Art', 'count' => 0]],
    'sizes' => [['label' => 'Small (6" - 8")'], ['label' => 'Medium (10" - 14")'], ['label' => 'Large (16" - 24")'], ['label' => 'Extra Large (30" - 36")'], ['label' => 'Custom Size']],
    'price_ranges' => [['label' => 'Under ₹1,000', 'min' => 0, 'max' => 1000], ['label' => '₹1,000 - ₹2,000', 'min' => 1000, 'max' => 2000], ['label' => '₹2,000 - ₹3,000', 'min' => 2000, 'max' => 3000], ['label' => '₹3,000 - ₹5,000', 'min' => 3000, 'max' => 5000], ['label' => '₹5,000 - ₹10,000', 'min' => 5000, 'max' => 10000], ['label' => 'Above ₹10,000', 'min' => 10000, 'max' => 999999]],
    'materials' => [['label' => 'POP Clay'], ['label' => 'MDF Board'], ['label' => 'Wooden Base'], ['label' => 'Canvas'], ['label' => 'Iron/Metal'], ['label' => 'Terracotta']],
    'ratings' => [['label' => '4 ★ & Above'], ['label' => '3 ★ & Above'], ['label' => '2 ★ & Above']],
    'sort_options' => [['label' => 'Featured'], ['label' => 'Price: Low to High'], ['label' => 'Price: High to Low'], ['label' => 'Name: A-Z'], ['label' => 'Name: Z-A'], ['label' => 'Newest First']],
];

// Product Variants Example
$productVariantsExample = [
    ['variant_id' => 206, 'product_id' => 1, 'size' => 'Small', 'dimension' => '6" - 8"', 'current_price' => '', 'old_price' => '', 'weight' => '', 'sku' => '', 'available' => 0],
    ['variant_id' => 207, 'product_id' => 1, 'size' => 'Medium', 'dimension' => '10" - 14"', 'current_price' => '', 'old_price' => '', 'weight' => '', 'sku' => '', 'available' => 0],
    ['variant_id' => 208, 'product_id' => 1, 'size' => 'Large', 'dimension' => '16" - 24"', 'current_price' => '', 'old_price' => '', 'weight' => '', 'sku' => '', 'available' => 0],
    ['variant_id' => 209, 'product_id' => 1, 'size' => 'Extra Large', 'dimension' => '30" - 36"', 'current_price' => '', 'old_price' => '', 'weight' => '', 'sku' => '', 'available' => 0],
];

function getProductById($productId) {
    global $homeFourPicksProducts, $topRateProducts, $topItemsProducts, $categoryPromoProducts, 
           $mostLovedProducts, $productsSectionProducts, $limitedTimeProducts, $favouriteCategoryProducts,
           $newArrivalsProducts;
    
    $allProducts = array_merge(
        $homeFourPicksProducts ?? [],
        $topRateProducts ?? [],
        $topItemsProducts ?? [],
        $categoryPromoProducts ?? [],
        $mostLovedProducts ?? [],
        $productsSectionProducts ?? [],
        $limitedTimeProducts ?? [],
        $favouriteCategoryProducts ?? [],
        $newArrivalsProducts ?? []
    );
    
    foreach ($allProducts as $product) {
        if (isset($product['id']) && $product['id'] == $productId) {
            $dbConnected = false;
            if (file_exists(__DIR__ . '/../admin/includes/db.php') && file_exists(__DIR__ . '/../config/database.php')) {
                try {
                    require_once __DIR__ . '/../admin/includes/db.php';
                    $db = getDB();
                    $stmt = $db->prepare("SELECT * FROM products WHERE id = ?");
                    $stmt->execute([$productId]);
                    $dbProduct = $stmt->fetch();
                    if ($dbProduct) {
                        $dbConnected = true;
                        $product['description'] = $dbProduct['description'] ?? '';
                        $product['materials'] = $dbProduct['materials'] ?? '';
                        $product['dimensions'] = $dbProduct['dimensions'] ?? '';
                        $product['weight'] = $dbProduct['weight'] ?? '';
                        $product['care_instructions'] = $dbProduct['care_instructions'] ?? '';
                        $product['sku'] = $dbProduct['sku'] ?? ('SKU-' . str_pad($product['id'], 3, '0', STR_PAD_LEFT));
                        
                        $imgs = $db->prepare("SELECT image_path FROM product_images WHERE product_id = ? ORDER BY sort_order");
                        $imgs->execute([$productId]);
                        $images = $imgs->fetchAll(PDO::FETCH_COLUMN);
                        $product['images'] = !empty($images) ? $images : [$product['image']];
                        
                        $sizes = $db->prepare("SELECT size_label FROM product_sizes WHERE product_id = ?");
                        $sizes->execute([$productId]);
                        $sizeLabels = $sizes->fetchAll(PDO::FETCH_COLUMN);
                        $product['size_options'] = !empty($sizeLabels) ? $sizeLabels : ['Small', 'Medium', 'Large', 'Extra Large'];
                        
                        $colors = $db->prepare("SELECT color_name as name, color_hex as hex, color_image as image FROM product_colors WHERE product_id = ?");
                        $colors->execute([$productId]);
                        $colorOpts = $colors->fetchAll();
                        $product['color_options'] = !empty($colorOpts) ? $colorOpts : [
                            ['name' => 'Natural White', 'hex' => '#F5F0E8', 'image' => ''],
                            ['name' => 'Cream Beige', 'hex' => '#E8D5B7', 'image' => ''],
                            ['name' => 'Terracotta', 'hex' => '#C67B5C', 'image' => ''],
                            ['name' => 'Multicolor', 'hex' => 'linear-gradient(135deg, #E8D5B7, #C67B5C, #8B5E3C)', 'image' => '']
                        ];
                        
                        $info = $db->prepare("SELECT info_key, info_value FROM product_additional_info WHERE product_id = ?");
                        $info->execute([$productId]);
                        $infoRows = $info->fetchAll();
                        $additionalInfo = [];
                        foreach ($infoRows as $row) {
                            $additionalInfo[$row['info_key']] = $row['info_value'];
                        }
                        $product['additional_info'] = !empty($additionalInfo) ? $additionalInfo : [];
                    }
                } catch (Exception $e) {
                    // DB not available, use defaults
                }
            }
            if (!$dbConnected) {
                $product['images'] = [$product['image']];
                $product['description'] = '';
                $product['materials'] = '';
                $product['dimensions'] = '';
                $product['weight'] = '';
                $product['care_instructions'] = '';
                $product['sku'] = 'SKU-' . str_pad($product['id'], 3, '0', STR_PAD_LEFT);
                $product['size_options'] = ['Small', 'Medium', 'Large', 'Extra Large'];
                $product['color_options'] = [['name' => 'Natural White', 'hex' => '#F5F0E8', 'image' => '']];
                $product['additional_info'] = [];
            }
            return $product;
        }
    }
    
    return [
        'id' => 1,
        'name' => 'Product',
        'category' => 'Lippan Art',
        'image' => 'images/product/p-1.jpeg',
        'images' => ['images/product/p-1.jpeg'],
        'current_price' => '₹0',
        'old_price' => '',
        'discount_percentage' => '',
        'discount_badge' => '',
        'rating' => 0,
        'reviews' => 0,
        'sold' => 0,
        'available' => 0,
        'description' => '',
        'materials' => '',
        'dimensions' => '',
        'weight' => '',
        'care_instructions' => '',
        'sku' => 'SKU-001',
        'size_options' => ['Small', 'Medium', 'Large'],
        'color_options' => [['name' => 'Natural White', 'hex' => '#F5F0E8']],
        'additional_info' => []
    ];
}

function getRelatedProducts($currentProductId, $category = null, $limit = 4) {
    global $homeFourPicksProducts, $topRateProducts, $topItemsProducts, $categoryPromoProducts, 
           $mostLovedProducts, $productsSectionProducts, $limitedTimeProducts, $favouriteCategoryProducts,
           $newArrivalsProducts;
    
    $allProducts = array_merge(
        $homeFourPicksProducts ?? [],
        $topRateProducts ?? [],
        $topItemsProducts ?? [],
        $categoryPromoProducts ?? [],
        $mostLovedProducts ?? [],
        $productsSectionProducts ?? [],
        $limitedTimeProducts ?? [],
        $favouriteCategoryProducts ?? [],
        $newArrivalsProducts ?? []
    );
    
    $related = [];
    foreach ($allProducts as $product) {
        if (isset($product['id']) && $product['id'] != $currentProductId) {
            if ($category === null || $product['category'] === $category) {
                $related[] = $product;
                if (count($related) >= $limit) break;
            }
        }
    }
    
    if (count($related) < $limit) {
        foreach ($allProducts as $product) {
            if (isset($product['id']) && $product['id'] != $currentProductId) {
                $found = false;
                foreach ($related as $r) {
                    if ($r['id'] == $product['id']) { $found = true; break; }
                }
                if (!$found) {
                    $related[] = $product;
                    if (count($related) >= $limit) break;
                }
            }
        }
    }
    
    return array_slice($related, 0, $limit);
}
?>