<?php
// Testimonial Data - AUTO-GENERATED BY ADMIN PANEL
// Do not edit manually. Changes will be overwritten.
// Last synced: 2026-05-17 16:43:53

$testimonials = [
    [
        'id' => 2,
        'name' => 'Rahul Rajput',
        'designation' => 'Customer',
        'content' => 'Absolutely beautiful craftsmanship! The mandala detailing looks even more elegant in real life. It completely transformed my living room wall and gives such a premium artistic vibe. Everyone who visits asks where I bought it from.',
        'image' => 'uploads/testimonials/test_1778961052_3c6d41a8.jpeg',
        'rating' => 5,
        'sort_order' => 0,
    ],
    [
        'id' => 3,
        'name' => 'Mohan Singh',
        'designation' => 'customer',
        'content' => 'The quality and finishing are amazing. The colors, mirror work, and handmade detailing feel very luxurious and authentic. Packaging was also very secure. Perfect decor piece for anyone who loves traditional art with a modern touch.',
        'image' => 'uploads/testimonials/test_1779024953_7ee48a13.jpeg',
        'rating' => 5,
        'sort_order' => 0,
    ],
    [
        'id' => 4,
        'name' => 'Savita kumari',
        'designation' => 'Customer',
        'content' => 'I purchased this for my studio entrance and it instantly became the highlight of the space. The design feels calming, classy, and very unique. You can clearly see the handmade effort in every detail',
        'image' => 'uploads/testimonials/test_1779024977_da00e904.jpeg',
        'rating' => 5,
        'sort_order' => 0,
    ],
];
?>